# Temat: Pandas — czyszczenie danych
Autor: Jan Pyka

In [17]:
import pandas as pd
import numpy as np
data = {
 'id_pracownika': [1,2,3,4,5,6,7,8,9,10,
 11,12,13,14,15,16,17,18,19,20,
 3,7,12,18,5, # duplikaty — te same id!
 21,22,23,24,25],
 'imie': ['Anna', 'Bartek', 'CELINA', 'darek', 'Ewa',
 'Filip', 'Gosia', 'HENRYK', 'irena', 'Jan',
 'Kasia', 'Leszek', 'Marta', 'norbert', 'OLGA',
 'Piotr', 'Renata', 'sławek', 'Teresa', 'Urszula',
 'CELINA', 'Gosia', 'Leszek', 'sławek', 'Ewa',
 'Wanda', 'Xawery', 'Yvonne', 'Zbyszek', 'Agata'],
 'dzial': ['Sprzedaz', 'IT', 'HR', 'sprzedaz', 'IT',
 'HR', 'Sprzedaz', 'it', 'HR', 'Sprzedaz',
 'IT', 'HR', 'sprzedaz', 'IT', 'HR',
 'Sprzedaz', 'it', 'HR', 'Sprzedaz', 'IT',
 'HR', 'Sprzedaz', 'HR', 'HR', 'IT',
 'Sprzedaz', 'IT', 'hr', 'Sprzedaz', 'IT'],
 'wynagrodzenie': ['4500', '6200', '3800', '5100', '7500',
 '4200', '5800', '6900', '3500', '4800',
 '7200', '4100', '5500', '6800', '3900',
 '5200', '4700', '6100', '3800', '5400',
 '3800', '5800', '4100', '6100', '7500',
 'brak', '5000', None, '4300', '6600'],
 'data_zatrudnienia': ['2020-03-15', '2019-07-22', '2021-01-10',
 '2018-05-30', '2022-11-01', '2020-08-14',
 '2019-12-05', '2021-06-18', '2017-09-23',
 '2023-02-07', '2020-04-11', '2018-11-28',
 '2022-07-15', '2019-03-19', '2021-10-08',
  '2020-06-25', '2018-08-31', '2022-02-14',
 '2019-05-07', '2021-09-20', '2021-01-10',
 '2019-12-05', '2018-11-28', '2022-02-14',
 '2022-11-01', '2023-01-15', '2022-05-20',
 None, '2020-10-11', '2019-08-03'],
 'ocena_roczna': [4.5, 3.8, None, 4.2, 5.0,
 3.5, 4.7, None, 4.1, 3.9,
 5.0, 4.3, 3.6, None, 4.8,
 3.7, 4.4, 4.9, None, 3.8,
 None, 4.7, 4.3, 4.9, 5.0,
 4.6, None, 4.9, 3.5, 4.1]
}
df = pd.DataFrame(data)
print(f"Wczytano dataset: {df.shape[0]} wierszy, {df.shape[1]} kolumn")
df.head(10)

Wczytano dataset: 30 wierszy, 6 kolumn

,id_pracownika,imie,dzial,wynagrodzenie,data_zatrudnienia,ocena_roczna
0,1,Anna,Sprzedaz,4500,2020-03-15,4.5
1,2,Bartek,IT,6200,2019-07-22,3.8
2,3,CELINA,HR,3800,2021-01-10,NaN
3,4,darek,sprzedaz,5100,2018-05-30,4.2
4,5,Ewa,IT,7500,2022-11-01,5.0
5,6,Filip,HR,4200,2020-08-14,3.5
6,7,Gosia,Sprzedaz,5800,2019-12-05,4.7
7,8,HENRYK,it,6900,2021-06-18,NaN
8,9,irena,HR,3500,2017-09-23,4.1
9,10,Jan,Sprzedaz,4800,2023-02-07,3.9

# Ćwiczenie 1: Brakujące wartości

### Zadanie 1a — Diagnoza

In [18]:
# 1. Wyświetl info() aby zobaczyć typy danych i liczbę wartości non-null
print(f'Info - wartosci non-null: {df.info()}\n')
# 2. Policz brakujące wartości w każdej kolumnie (isna().sum())
print(f'Brakujące wartości dla każdej kolumny:\n{df.isna().sum()}\n')
# 3. Oblicz procent braków per kolumna (zaokrąglij do 1 miejsca po przecinku)
print(f'Brakujące wartości % per kolumna:\n{round(df.isna().sum() / len(df) * 100,1)}\n')
# 4. Wyświetl wiersze, które mają przynajmniej jeden brak (any(axis=1))
print(f'Wiersze gdzie jest min 1 brakujaca wartosc:\n{df[df.isna().any(axis=1)]}')

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_pracownika      30 non-null     int64
 1   imie               30 non-null     str
 2   dzial              30 non-null     str
 3   wynagrodzenie      29 non-null     str
 4   data_zatrudnienia  29 non-null     str
 5   ocena_roczna       24 non-null     float64
dtypes: float64(1), int64(1), str(4)
memory usage: 1.5 KB
Info - wartosci non-null: None

Brakujące wartości dla każdej kolumny:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        1
data_zatrudnienia    1
ocena_roczna         6
dtype: int64

Brakujące wartości % per kolumna:
id_pracownika         0.0
imie                  0.0
dzial                 0.0
wynagrodzenie         3.3
data_zatrudnienia     3.3
ocena_roczna         20.0
dtype: float64

Wiersze gdzie jest min 1 brakujaca wartosc:
    id_pracownika     imie     dzial wynagrodzenie data_zatrudnienia  \
2               3   CELINA        HR          3800        2021-01-10
7               8   HENRYK        it          6900        2021-06-18
13             14  norbert        IT          6800        2019-03-19
18             19   Teresa  Sprzedaz          3800        2019-05-07
20              3   CELINA        HR          3800        2021-01-10
26             22   Xawery        IT          5000        2022-05-20
27             23   Yvonne        hr           NaN               NaN

    ocena_roczna
2            NaN
7            NaN
13           NaN
18           NaN
20           NaN
26           NaN
27           4.9

### Zadanie 1b — Wynagrodzenie: 'brak' i None

In [25]:
# 1. Sprawdź unikalne wartości w kolumnie wynagrodzenie
print(f'Unikalne wartości w kolumnie wynagrodzenie:\n{df['wynagrodzenie'].unique()}\n')
# 2. Zamień 'brak' na np.nan
df['wynagrodzenie'] = df['wynagrodzenie'].replace('brak', np.nan)
# 3. Skonwertuj wynagrodzenie na float używając pd.to_numeric z errors='coerce'
df['wynagrodzenie'] = pd.to_numeric(df['wynagrodzenie'], errors='coerce')
# 4. Ile NaN jest teraz w wynagrodzenie?
print(f'Liczba NaN: {df['wynagrodzenie'].isna().sum()}')

Unikalne wartości w kolumnie wynagrodzenie:
[4500. 6200. 3800. 5100. 7500. 4200. 5800. 6900. 3500. 4800. 7200. 4100.
 5500. 6800. 3900. 5200. 4700. 6100. 5400.   nan 5000. 4300. 6600.]

Liczba NaN: 2

### Zadanie 1c — Strategie fillna

In [33]:
# 1. Oblicz medianę wynagrodzenia (ignorując NaN — to domyślne zachowanie)
mediana = df['wynagrodzenie'].median()
print(f'Mediana wynosi: {mediana}\n')
# 2. Wypełnij NaN w wynagrodzeniu medianą
df['wynagrodzenie'] = df['wynagrodzenie'].fillna(mediana)
# 3. Oblicz średnią ocena_roczna (zaokrąglij do 2 miejsc)
srednia = round(df['ocena_roczna'].mean(), 2)
print(f"Srednia ocena: {srednia}")
# 4. Wypełnij NaN w ocena_roczna średnią
df['ocena_roczna'] = df['ocena_roczna'].fillna(srednia)
print('\n')
# 5. Sprawdź ile NaN zostało w każdej kolumnie
print(f'Ilosc NaN w kazdej kolumnie:\n{df.isna().sum()}')

Mediana wynosi: 5150.0

Srednia ocena: 4.34


Ilosc NaN w kazdej kolumnie:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

### Zadanie 1d — dropna

In [32]:
# 1. Ile wierszy zostanie po usunięciu wierszy z brakiem w 'data_zatrudnienia'?
df_bez_brakow = df.dropna(subset=['data_zatrudnienia'])
print(f'Ilosc wierszy w data_zatrudnienia bez brakow: {len(df_bez_brakow)}')
# Uwaga: NIE nadpisujemy df — tylko liczymy, ile wierszy by zostało

Ilosc wierszy w data_zatrudnienia bez brakow: 29

# Ćwiczenie 2: Duplikaty + konwersja typów

In [34]:
# Zacznij od świeżej kopii
df2 = pd.DataFrame(data) # ta sama definicja 'data' co wyżej
# Najpierw napraw wynagrodzenie (tak samo jak w Ćw. 1b)
df2['wynagrodzenie'] = df2['wynagrodzenie'].replace('brak', np.nan)
df2['wynagrodzenie'] = pd.to_numeric(df2['wynagrodzenie'], errors='coerce')

### Zadanie 2a — Wykrycie duplikatów

In [41]:
# 1. Ile pełnych duplikatów (identycznych wierszy) ma dataset?
print(f'Ilosc pelnych duplikatow: {df2.duplicated().sum()}\n')
# 2. Wyświetl zduplikowane wiersze (te które są kopiami)
print(f'Wszystkie zduplikowane wiersze:\n{df2[df2.duplicated()]}\n')
# 3. Czy liczba duplikatów wg id_pracownika jest taka sama?
print(f'Ilosc duplikatow wg id_pracownika: {df2.duplicated(subset=['id_pracownika']).sum()}')
# 4. Wyświetl ile razy pojawia się każde id_pracownika
print(f'Ilosc pojawienia sie kazdego id_pracownika:\n{df2['id_pracownika'].value_counts().sort_index()}')

Ilosc pelnych duplikatow: 5

Wszystkie zduplikowane wiersze:
    id_pracownika    imie     dzial  wynagrodzenie data_zatrudnienia  \
20              3  CELINA        HR         3800.0        2021-01-10
21              7   Gosia  Sprzedaz         5800.0        2019-12-05
22             12  Leszek        HR         4100.0        2018-11-28
23             18  sławek        HR         6100.0        2022-02-14
24              5     Ewa        IT         7500.0        2022-11-01

    ocena_roczna
20           NaN
21           4.7
22           4.3
23           4.9
24           5.0

Ilosc duplikatow wg id_pracownika: 5
Ilosc pojawienia sie kazdego id_pracownika:
id_pracownika
1     1
2     1
3     2
4     1
5     2
6     1
7     2
8     1
9     1
10    1
11    1
12    2
13    1
14    1
15    1
16    1
17    1
18    2
19    1
20    1
21    1
22    1
23    1
24    1
25    1
Name: count, dtype: int64

### Zadanie 2b — Usunięcie duplikatów

In [42]:
# 1. Usuń pełne duplikaty i zresetuj indeks
df2 = df2.drop_duplicates().reset_index(drop=True)
# 2. Wyświetl nowy kształt DataFrame
print(df2.shape)

(25, 6)

### Zadanie 2c — Konwersja daty

In [48]:
# 1. Sprawdź aktualny typ kolumny data_zatrudnienia
print(f'Aktualny typ kolumny data_zatrudnienia: {df2['data_zatrudnienia'].dtype}\n')
# 2. Skonwertuj na datetime
df2['data_zatrudnienia'] = pd.to_datetime(df2['data_zatrudnienia'], errors='coerce')
# 3. Sprawdź nowy typ
print(f'Aktualny typ kolumny data_zatrudnienia: {df2['data_zatrudnienia'].dtype}\n')
# 4. Wyodrębnij rok zatrudnienia do nowej kolumny 'rok_zatrudnienia'
df2['rok_zatrudnienia'] = df2['data_zatrudnienia'].dt.year
print(df2['rok_zatrudnienia'].dropna().unique())

Aktualny typ kolumny data_zatrudnienia: datetime64[us]

Aktualny typ kolumny data_zatrudnienia: datetime64[us]

[2020. 2019. 2021. 2018. 2022. 2017. 2023.]

### Zadanie 2d — Pytanie biznesowe

In [63]:
# Używając df2 po czyszczeniu:
# 1. Ile pracowników zostało zatrudnionych po 2021 roku (włącznie)?
print(f'Ilosc pracownikow zatrudnionych po 2021: {len(df2.query('rok_zatrudnienia >= 2021'))}\n')
# 2. Ile pracowników ma wynagrodzenie powyżej 6000?
# Uwaga: najpierw wyczyść dzial — str.strip().str.title()
df2['dzial'] = df2['dzial'].str.strip().str.title()
print(f'Ilosc pracownikow zarabiajacych > 6000: {len(df2.query('wynagrodzenie > 6000'))}\n')
# 3. Ilu pracowników jest w dziale 'It' (po title())?
print(f'Ilosc pracownikow w dziale IT: {len(df2[df2["dzial"] == "It"])}')

Ilosc pracownikow zatrudnionych po 2021: 10

Ilosc pracownikow zarabiajacych > 6000: 7

Ilosc pracownikow w dziale IT: 9

# Ćwiczenie 3: Pełny pipeline czyszczenia

In [65]:
df_clean = pd.DataFrame(data) # zacznij od świeżego df
# KROK 1: Zamień 'brak' na np.nan i skonwertuj wynagrodzenie na float
df_clean['wynagrodzenie'] = pd.to_numeric(df_clean['wynagrodzenie'], errors='coerce')
# KROK 2: Usuń duplikaty (drop_duplicates) i zresetuj indeks
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
# KROK 3: Wypełnij NaN w wynagrodzeniu medianą
mediana = df_clean['wynagrodzenie'].median()
df_clean['wynagrodzenie'] = df_clean['wynagrodzenie'].fillna(mediana)
# KROK 4: Oblicz średnią ocena_roczna i wypełnij NaN tą średnią
srednia = round(df_clean['ocena_roczna'].mean(), 2)
df_clean['ocena_roczna'] = df_clean['ocena_roczna'].fillna(srednia)
# KROK 5: Wyczyść kolumnę 'imie': str.strip() + str.title()
df_clean['imie'] = df_clean['imie'].str.strip().str.title()
# KROK 6: Wyczyść kolumnę 'dzial':
# a) str.strip() + str.title()
df_clean['dzial'] = df_clean['dzial'].str.strip().str.title()
# b) str.replace('Hr', 'HR', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('Hr','HR',regex=False)
# c) str.replace('It', 'IT', regex=False)
df_clean['dzial'] = df_clean['dzial'].str.replace('It','IT',regex=False)
# KROK 7: Skonwertuj 'data_zatrudnienia' na datetime (errors='coerce')
df_clean['data_zatrudnienia'] = pd.to_datetime(df_clean['data_zatrudnienia'], errors='coerce')
# WERYFIKACJA — uruchom te linijki żeby sprawdzić wyniki:
print("=== WERYFIKACJA ===")
print(f"Shape: {df_clean.shape}")
print(f"\nDtypes:\n{df_clean.dtypes}")
print(f"\nNaN per kolumna:\n{df_clean.isna().sum()}")
print(f"\nUnikalne działy: {sorted(df_clean['dzial'].unique())}")
print(f"\nPierwsze imiona: {df_clean['imie'].tolist()[:8]}")

=== WERYFIKACJA ===
Shape: (25, 6)

Dtypes:
id_pracownika                 int64
imie                            str
dzial                           str
wynagrodzenie               float64
data_zatrudnienia    datetime64[us]
ocena_roczna                float64
dtype: object

NaN per kolumna:
id_pracownika        0
imie                 0
dzial                0
wynagrodzenie        0
data_zatrudnienia    1
ocena_roczna         0
dtype: int64

Unikalne działy: ['HR', 'IT', 'Sprzedaz']

Pierwsze imiona: ['Anna', 'Bartek', 'Celina', 'Darek', 'Ewa', 'Filip', 'Gosia', 'Henryk']

### Pytania biznesowe

In [71]:
# Używając df_clean:
# Pytanie 1: Jakie jest średnie wynagrodzenie per dział?
print(f'Srednie wynagrodzenie per dzial:\n{df_clean.groupby('dzial')['wynagrodzenie'].mean().round(2)}\n')
# Pytanie 2: Jaka jest średnia ocena per dział?
print(f'Srednia ocena per dzial:\n{df_clean.groupby('dzial')['ocena_roczna'].mean().round(2)}\n')
# Pytanie 3: Kto jest najlepiej opłacany (top 3)?
print(f'Najlepiej oplacany (top3):\n{df_clean.nlargest(3, 'wynagrodzenie')[['imie', 'dzial','wynagrodzenie']]}\n')
# Pytanie 4: Ilu pracowników jest w każdym dziale?
print(f'Ilosc pracownikow w kazdym dziale:\n{df_clean['dzial'].value_counts()}\n')

Srednie wynagrodzenie per dzial:
dzial
HR          4385.71
IT          6255.56
Sprzedaz    4900.00
Name: wynagrodzenie, dtype: float64

Srednia ocena per dzial:
dzial
HR          4.39
IT          4.32
Sprzedaz    4.11
Name: ocena_roczna, dtype: float64

Najlepiej oplacany (top3):
      imie dzial  wynagrodzenie
4      Ewa    IT         7500.0
10   Kasia    IT         7200.0
7   Henryk    IT         6900.0

Ilosc pracownikow w kazdym dziale:
dzial
Sprzedaz    9
IT          9
HR          7
Name: count, dtype: int64

# Ćwiczenie 4: Operacje na tekstach + commit

### Zadanie 4a — Diagnoza przed czyszczeniem

In [ ]:
df_str = pd.DataFrame(data) # świeża kopia
# 1. Ile imion jest zapisanych WSZYSTKIMI WIELKIMI LITERAMI?
print(f'Liczba imion wielkie litery: {df_str['imie'].str.isupper().sum()}\n')
# 2. Ile imion zaczyna się małą literą?
print(f'Liczba imion zaczynajace sie mala litera: {df_str['imie'].str[0].str.islower().sum()}\n')
# 3. Ile wierszy ma 'sprzedaz' w kolumnie dzial (niezależnie od wielkości)?
print(f'Liczba wierszy zawierajaca sprzedaz w kolumnie dzial: {df_str['dzial'].str.lower().str.contains('sprzedaz').sum()}')

Liczba imion wielkie litery: 4

Liczba imion zaczynajace sie mala litera: 5

Liczba wierszy zawierajaca sprzedaz w kolumnie dzial: 10

### Zadanie 4b — Czyszczenie i analiza

In [134]:
# 1. Wyczyść imie: strip() + title()
df_str['imie'] = df_str['imie'].str.strip().str.title()
# 2. Wyczyść dzial: strip() + title() + replace
df_str['dzial'] = df_str['dzial'].str.strip().str.title()
df_str['dzial'] = df_str['dzial'].str.replace('Hr', 'HR', regex=False)
df_str['dzial'] = df_str['dzial'].str.replace('It', 'IT', regex=False)
# 3. Ile pracowników ma imię zaczynające się na 'A'?
print(f'Ilosc prac. ma imie na A: {len(df_str[df_str["imie"].str.startswith("A")])}')
# 4. Utwórz kolumnę 'dlugosc_imienia' z długością imienia
df_str['dlugosc_imienia'] = df_str['imie'].str.len()
print(df_str['dlugosc_imienia'].describe())
# 5. Kto ma najdłuższe imię? (nlargest lub sort_values)
df_str.nlargest(1,'dlugosc_imienia')[['imie','dlugosc_imienia']]

Ilosc prac. ma imie na A: 2
count    30.000000
mean      5.333333
std       1.093345
min       3.000000
25%       5.000000
50%       5.500000
75%       6.000000
max       7.000000
Name: dlugosc_imienia, dtype: float64

       imie  dlugosc_imienia
13  Norbert                7

### Zadanie 4c — str.contains z wzorcem

In [137]:
# str.contains() może używać wyrażeń regularnych!
# 1. Znajdź pracowników z działów IT lub HR (jeden zawiera drugi wzorzec)
print(df_str[df_str['dzial'].str.contains('IT|HR')])

    id_pracownika     imie dzial wynagrodzenie data_zatrudnienia  \
1               2   Bartek    IT          6200        2019-07-22
2               3   Celina    HR          3800        2021-01-10
4               5      Ewa    IT          7500        2022-11-01
5               6    Filip    HR          4200        2020-08-14
7               8   Henryk    IT          6900        2021-06-18
8               9    Irena    HR          3500        2017-09-23
10             11    Kasia    IT          7200        2020-04-11
11             12   Leszek    HR          4100        2018-11-28
13             14  Norbert    IT          6800        2019-03-19
14             15     Olga    HR          3900        2021-10-08
16             17   Renata    IT          4700        2018-08-31
17             18   Sławek    HR          6100        2022-02-14
19             20  Urszula    IT          5400        2021-09-20
20              3   Celina    HR          3800        2021-01-10
22             12   Leszek    HR          4100        2018-11-28
23             18   Sławek    HR          6100        2022-02-14
24              5      Ewa    IT          7500        2022-11-01
26             22   Xawery    IT          5000        2022-05-20
27             23   Yvonne    HR           NaN               NaN
29             25    Agata    IT          6600        2019-08-03

    ocena_roczna  dlugosc_imienia
1            3.8                6
2            NaN                6
4            5.0                3
5            3.5                5
7            NaN                6
8            4.1                5
10           5.0                5
11           4.3                6
13           NaN                7
14           4.8                4
16           4.4                6
17           4.9                6
19           3.8                7
20           NaN                6
22           4.3                6
23           4.9                6
24           5.0                3
26           NaN                6
27           4.9                6
29           4.1                5

In [139]:
# 2. Znajdź imiona zawierające literę 'a' (małą lub dużą)
print(df_str[df_str['imie'].str.contains('a', case=False)])

    id_pracownika     imie     dzial wynagrodzenie data_zatrudnienia  \
0               1     Anna  Sprzedaz          4500        2020-03-15
1               2   Bartek        IT          6200        2019-07-22
2               3   Celina        HR          3800        2021-01-10
3               4    Darek  Sprzedaz          5100        2018-05-30
4               5      Ewa        IT          7500        2022-11-01
6               7    Gosia  Sprzedaz          5800        2019-12-05
8               9    Irena        HR          3500        2017-09-23
9              10      Jan  Sprzedaz          4800        2023-02-07
10             11    Kasia        IT          7200        2020-04-11
12             13    Marta  Sprzedaz          5500        2022-07-15
14             15     Olga        HR          3900        2021-10-08
16             17   Renata        IT          4700        2018-08-31
17             18   Sławek        HR          6100        2022-02-14
18             19   Teresa  Sprzedaz          3800        2019-05-07
19             20  Urszula        IT          5400        2021-09-20
20              3   Celina        HR          3800        2021-01-10
21              7    Gosia  Sprzedaz          5800        2019-12-05
23             18   Sławek        HR          6100        2022-02-14
24              5      Ewa        IT          7500        2022-11-01
25             21    Wanda  Sprzedaz          brak        2023-01-15
26             22   Xawery        IT          5000        2022-05-20
29             25    Agata        IT          6600        2019-08-03

    ocena_roczna  dlugosc_imienia
0            4.5                4
1            3.8                6
2            NaN                6
3            4.2                5
4            5.0                3
6            4.7                5
8            4.1                5
9            3.9                3
10           5.0                5
12           3.6                5
14           4.8                4
16           4.4                6
17           4.9                6
18           NaN                6
19           3.8                7
20           NaN                6
21           4.7                5
23           4.9                6
24           5.0                3
25           4.6                5
26           NaN                6
29           4.1                5

In [141]:
# 3. Ile pracowników ma imię kończące się na 'a'?
print(f'Ilosc prac. z imieniem konczacym sie na a: {len(df_str[df_str['imie'].str.endswith('a')])}')
# Wskazówka: str.endswith('a') lub str.contains('a$', regex=True)

Ilosc prac. z imieniem konczacym sie na a: 16